name: First Workflow
on:
  workflow_dispatch:
  push:
    branches: [ master ]
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: print greeting
        run: echo "MedOx"
      - name: print goodbye
        run: echo "Done. Bye!!"
